export {default as postServiceFactory} from './PostService'
export {PostService as POST} from './PostService'
export {default as getServiceFactory} from './GetService'
export {GetService as GET} from './GetService'
export {default as deleteServiceFactory} from './DeleteService'
export {DeleteService as DELETE} from './DeleteService'
